import _ from 'underscore';

export type City = {
    name: string,
    isCapital: boolean,
}

export type State = {
    name: string,
    cities: City[],
}

export const STATES: State[] =
    [
        { "name": "Alabama", "cities": [{ "name": "Huntsville", "isCapital": false }, { "name": "Montgomery", "isCapital": true }, { "name": "Birmingham", "isCapital": false }, { "name": "Mobile", "isCapital": false }, { "name": "Tuscaloosa", "isCapital": false }] },
        { "name": "Alaska", "cities": [{ "name": "Anchorage", "isCapital": false }, { "name": "Juneau", "isCapital": true }, { "name": "Fairbanks", "isCapital": false }, { "name": "Wasilla", "isCapital": false }, { "name": "Sitka", "isCapital": false }] },
        { "name": "Arizona", "cities": [{ "name": "Phoenix", "isCapital": true }, { "name": "Tucson", "isCapital": false }, { "name": "Mesa", "isCapital": false }, { "name": "Chandler", "isCapital": false }, { "name": "Scottsdale", "isCapital": false }] },
        { "name": "Arkansas", "cities": [{ "name": "Little Rock", "isCapital": true }, { "name": "Fayetteville", "isCapital": false }, { "name": "Fort Smith", "isCapital": false }, { "name": "Springdale", "isCapital": false }, { "name": "Jonesboro", "isCapital": false }] },
        { "name": "California", "cities": [{ "name": "Los Angeles", "isCapital": false }, { "name": "San Diego", "isCapital": false }, { "name": "San Jose", "isCapital": false }, { "name": "San Francisco", "isCapital": false }, { "name": "Fresno", "isCapital": false }, { "name": "Sacramento", "isCapital": true }] },
        { "name": "Colorado", "cities": [{ "name": "Denver", "isCapital": true }, { "name": "Colorado Springs", "isCapital": false }, { "name": "Aurora", "isCapital": false }, { "name": "Fort Collins", "isCapital": false }, { "name": "Lakewood", "isCapital": false }] },
        { "name": "Connecticut", "cities": [{ "name": "Bridgeport", "isCapital": false }, { "name": "Stamford", "isCapital": false }, { "name": "New Haven", "isCapital": false }, { "name": "Hartford", "isCapital": true }, { "name": "Waterbury", "isCapital": false }] },
        { "name": "Delaware", "cities": [{ "name": "Wilmington", "isCapital": false }, { "name": "Dover", "isCapital": true }, { "name": "Newark", "isCapital": false }, { "name": "Middletown", "isCapital": false }, { "name": "Smyrna", "isCapital": false }] },
        { "name": "Florida", "cities": [{ "name": "Jacksonville", "isCapital": false }, { "name": "Miami", "isCapital": false }, { "name": "Tampa", "isCapital": false }, { "name": "Orlando", "isCapital": false }, { "name": "St. Petersburg", "isCapital": false }, { "name": "Tallahassee", "isCapital": true }] },
        { "name": "Georgia", "cities": [{ "name": "Atlanta", "isCapital": true }, { "name": "Columbus", "isCapital": false }, { "name": "Augusta", "isCapital": false }, { "name": "Macon", "isCapital": false }, { "name": "Savannah", "isCapital": false }] },
        { "name": "Guam", "cities": [{ "name": "Dededo", "isCapital": false }, { "name": "Yigo", "isCapital": false }, { "name": "Tamuning", "isCapital": false }, { "name": "Mangilao", "isCapital": false }, { "name": "Barrigada", "isCapital": false }, { "name": "Hagåtña", "isCapital": true }] },
        { "name": "Hawaii", "cities": [{ "name": "Honolulu", "isCapital": true }, { "name": "East Honolulu", "isCapital": false }, { "name": "Pearl City", "isCapital": false }, { "name": "Hilo", "isCapital": false }, { "name": "Kailua", "isCapital": false }] },
        { "name": "Idaho", "cities": [{ "name": "Boise", "isCapital": true }, { "name": "Meridian", "isCapital": false }, { "name": "Nampa", "isCapital": false }, { "name": "Idaho Falls", "isCapital": false }, { "name": "Caldwell", "isCapital": false }] },
        { "name": "Illinois", "cities": [{ "name": "Chicago", "isCapital": false }, { "name": "Aurora", "isCapital": false }, { "name": "Naperville", "isCapital": false }, { "name": "Joliet", "isCapital": false }, { "name": "Rockford", "isCapital": false }, { "name": "Springfield", "isCapital": true }] },
        { "name": "Indiana", "cities": [{ "name": "Indianapolis", "isCapital": true }, { "name": "Fort Wayne", "isCapital": false }, { "name": "Evansville", "isCapital": false }, { "name": "South Bend", "isCapital": false }, { "name": "Carmel", "isCapital": false }] },
        { "name": "Iowa", "cities": [{ "name": "Des Moines", "isCapital": true }, { "name": "Cedar Rapids", "isCapital": false }, { "name": "Davenport", "isCapital": false }, { "name": "Sioux City", "isCapital": false }, { "name": "Iowa City", "isCapital": false }] },
        { "name": "Kansas", "cities": [{ "name": "Wichita", "isCapital": false }, { "name": "Overland Park", "isCapital": false }, { "name": "Kansas City", "isCapital": false }, { "name": "Olathe", "isCapital": false }, { "name": "Topeka", "isCapital": true }] },
        { "name": "Kentucky", "cities": [{ "name": "Louisville", "isCapital": false }, { "name": "Lexington", "isCapital": false }, { "name": "Bowling Green", "isCapital": false }, { "name": "Owensboro", "isCapital": false }, { "name": "Covington", "isCapital": false }, { "name": "Frankfort", "isCapital": true }] },
        { "name": "Louisiana", "cities": [{ "name": "New Orleans", "isCapital": false }, { "name": "Baton Rouge", "isCapital": true }, { "name": "Shreveport", "isCapital": false }, { "name": "Lafayette", "isCapital": false }, { "name": "Lake Charles", "isCapital": false }] },
        { "name": "Maine", "cities": [{ "name": "Portland", "isCapital": false }, { "name": "Lewiston", "isCapital": false }, { "name": "Bangor", "isCapital": false }, { "name": "South Portland", "isCapital": false }, { "name": "Auburn", "isCapital": false }, { "name": "Augusta", "isCapital": true }] },
        { "name": "Maryland", "cities": [{ "name": "Baltimore", "isCapital": false }, { "name": "Columbia", "isCapital": false }, { "name": "Germantown", "isCapital": false }, { "name": "Silver Spring", "isCapital": false }, { "name": "Waldorf", "isCapital": false }, { "name": "Annapolis", "isCapital": true }] },
        { "name": "Massachusetts", "cities": [{ "name": "Boston", "isCapital": true }, { "name": "Worcester", "isCapital": false }, { "name": "Springfield", "isCapital": false }, { "name": "Cambridge", "isCapital": false }, { "name": "Lowell", "isCapital": false }] },
        { "name": "Michigan", "cities": [{ "name": "Detroit", "isCapital": false }, { "name": "Grand Rapids", "isCapital": false }, { "name": "Warren", "isCapital": false }, { "name": "Sterling Heights", "isCapital": false }, { "name": "Ann Arbor", "isCapital": false }, { "name": "Lansing", "isCapital": true }] },
        { "name": "Minnesota", "cities": [{ "name": "Minneapolis", "isCapital": false }, { "name": "Saint Paul", "isCapital": true }, { "name": "Rochester", "isCapital": false }, { "name": "Duluth", "isCapital": false }, { "name": "Bloomington", "isCapital": false }] },
        { "name": "Mississippi", "cities": [{ "name": "Jackson", "isCapital": true }, { "name": "Gulfport", "isCapital": false }, { "name": "Southaven", "isCapital": false }, { "name": "Biloxi", "isCapital": false }, { "name": "Hattiesburg", "isCapital": false }] },
        { "name": "Missouri", "cities": [{ "name": "Kansas City", "isCapital": false }, { "name": "Saint Louis", "isCapital": false }, { "name": "Springfield", "isCapital": false }, { "name": "Columbia", "isCapital": false }, { "name": "Independence", "isCapital": false }, { "name": "Jefferson City", "isCapital": true }] },
        { "name": "Montana", "cities": [{ "name": "Billings", "isCapital": false }, { "name": "Missoula", "isCapital": false }, { "name": "Great Falls", "isCapital": false }, { "name": "Bozeman", "isCapital": false }, { "name": "Butte", "isCapital": false }, { "name": "Helena", "isCapital": true }] },
        { "name": "Nebraska", "cities": [{ "name": "Omaha", "isCapital": false }, { "name": "Lincoln", "isCapital": true }, { "name": "Bellevue", "isCapital": false }, { "name": "Grand Island", "isCapital": false }, { "name": "Kearney", "isCapital": false }] },
        { "name": "Nevada", "cities": [{ "name": "Las Vegas", "isCapital": false }, { "name": "Henderson", "isCapital": false }, { "name": "Reno", "isCapital": false }, { "name": "North Las Vegas", "isCapital": false }, { "name": "Paradise", "isCapital": false }, { "name": "Carson City", "isCapital": true }] },
        { "name": "New Hampshire", "cities": [{ "name": "Manchester", "isCapital": false }, { "name": "Nashua", "isCapital": false }, { "name": "Concord", "isCapital": true }, { "name": "Dover", "isCapital": false }, { "name": "Rochester", "isCapital": false }] },
        { "name": "New Jersey", "cities": [{ "name": "Newark", "isCapital": false }, { "name": "Jersey City", "isCapital": false }, { "name": "Paterson", "isCapital": false }, { "name": "Elizabeth", "isCapital": false }, { "name": "Edison", "isCapital": false }, { "name": "Trenton", "isCapital": true }] },
        { "name": "New Mexico", "cities": [{ "name": "Albuquerque", "isCapital": false }, { "name": "Las Cruces", "isCapital": false }, { "name": "Rio Rancho", "isCapital": false }, { "name": "Santa Fe", "isCapital": true }, { "name": "Roswell", "isCapital": false }] },
        { "name": "New York", "cities": [{ "name": "New York", "isCapital": false }, { "name": "Buffalo", "isCapital": false }, { "name": "Yonkers", "isCapital": false }, { "name": "Rochester", "isCapital": false }, { "name": "Syracuse", "isCapital": false }, { "name": "Albany", "isCapital": true }] },
        { "name": "North Carolina", "cities": [{ "name": "Charlotte", "isCapital": false }, { "name": "Raleigh", "isCapital": true }, { "name": "Greensboro", "isCapital": false }, { "name": "Durham", "isCapital": false }, { "name": "Winston-Salem", "isCapital": false }] },
        { "name": "North Dakota", "cities": [{ "name": "Fargo", "isCapital": false }, { "name": "Bismarck", "isCapital": true }, { "name": "Grand Forks", "isCapital": false }, { "name": "Minot", "isCapital": false }, { "name": "West Fargo", "isCapital": false }] },
        { "name": "Ohio", "cities": [{ "name": "Columbus", "isCapital": true }, { "name": "Cleveland", "isCapital": false }, { "name": "Cincinnati", "isCapital": false }, { "name": "Toledo", "isCapital": false }, { "name": "Akron", "isCapital": false }] },
        { "name": "Oklahoma", "cities": [{ "name": "Oklahoma City", "isCapital": true }, { "name": "Tulsa", "isCapital": false }, { "name": "Norman", "isCapital": false }, { "name": "Broken Arrow", "isCapital": false }, { "name": "Edmond", "isCapital": false }] },
        { "name": "Oregon", "cities": [{ "name": "Portland", "isCapital": false }, { "name": "Salem", "isCapital": true }, { "name": "Eugene", "isCapital": false }, { "name": "Gresham", "isCapital": false }, { "name": "Hillsboro", "isCapital": false }] },
        { "name": "Pennsylvania", "cities": [{ "name": "Philadelphia", "isCapital": false }, { "name": "Pittsburgh", "isCapital": false }, { "name": "Allentown", "isCapital": false }, { "name": "Erie", "isCapital": false }, { "name": "Reading", "isCapital": false }, { "name": "Harrisburg", "isCapital": true }] },
        { "name": "Puerto Rico", "cities": [{ "name": "San Juan", "isCapital": true }, { "name": "Bayamón", "isCapital": false }, { "name": "Carolina", "isCapital": false }, { "name": "Ponce", "isCapital": false }, { "name": "Caguas", "isCapital": false }] },
        { "name": "Rhode Island", "cities": [{ "name": "Providence", "isCapital": true }, { "name": "Cranston", "isCapital": false }, { "name": "Warwick", "isCapital": false }, { "name": "Pawtucket", "isCapital": false }, { "name": "East Providence", "isCapital": false }] },
        { "name": "South Carolina", "cities": [{ "name": "Charleston", "isCapital": false }, { "name": "Columbia", "isCapital": true }, { "name": "North Charleston", "isCapital": false }, { "name": "Mount Pleasant", "isCapital": false }, { "name": "Rock Hill", "isCapital": false }] },
        { "name": "South Dakota", "cities": [{ "name": "Sioux Falls", "isCapital": false }, { "name": "Rapid City", "isCapital": false }, { "name": "Aberdeen", "isCapital": false }, { "name": "Brookings", "isCapital": false }, { "name": "Watertown", "isCapital": false }, { "name": "Pierre", "isCapital": true }] },
        { "name": "Tennessee", "cities": [{ "name": "Nashville", "isCapital": true }, { "name": "Memphis", "isCapital": false }, { "name": "Knoxville", "isCapital": false }, { "name": "Chattanooga", "isCapital": false }, { "name": "Clarksville", "isCapital": false }] },
        { "name": "Texas", "cities": [{ "name": "Houston", "isCapital": false }, { "name": "San Antonio", "isCapital": false }, { "name": "Dallas", "isCapital": false }, { "name": "Austin", "isCapital": true }, { "name": "Fort Worth", "isCapital": false }] },
        { "name": "Utah", "cities": [{ "name": "Salt Lake City", "isCapital": true }, { "name": "West Valley City", "isCapital": false }, { "name": "Provo", "isCapital": false }, { "name": "West Jordan", "isCapital": false }, { "name": "Orem", "isCapital": false }] },
        { "name": "Vermont", "cities": [{ "name": "Burlington", "isCapital": false }, { "name": "South Burlington", "isCapital": false }, { "name": "Colchester", "isCapital": false }, { "name": "Rutland", "isCapital": false }, { "name": "Bennington", "isCapital": false }, { "name": "Montpelier", "isCapital": true }] },
        { "name": "Virginia", "cities": [{ "name": "Virginia Beach", "isCapital": false }, { "name": "Norfolk", "isCapital": false }, { "name": "Chesapeake", "isCapital": false }, { "name": "Richmond", "isCapital": true }, { "name": "Arlington", "isCapital": false }] },
        { "name": "Washington", "cities": [{ "name": "Seattle", "isCapital": false }, { "name": "Spokane", "isCapital": false }, { "name": "Tacoma", "isCapital": false }, { "name": "Vancouver", "isCapital": false }, { "name": "Bellevue", "isCapital": false }, { "name": "Olympia", "isCapital": true }] },
        { "name": "West Virginia", "cities": [{ "name": "Charleston", "isCapital": true }, { "name": "Huntington", "isCapital": false }, { "name": "Morgantown", "isCapital": false }, { "name": "Parkersburg", "isCapital": false }, { "name": "Wheeling", "isCapital": false }] },
        { "name": "Wisconsin", "cities": [{ "name": "Milwaukee", "isCapital": false }, { "name": "Madison", "isCapital": true }, { "name": "Green Bay", "isCapital": false }, { "name": "Kenosha", "isCapital": false }, { "name": "Racine", "isCapital": false }] },
        { "name": "Wyoming", "cities": [{ "name": "Cheyenne", "isCapital": true }, { "name": "Casper", "isCapital": false }, { "name": "Laramie", "isCapital": false }, { "name": "Gillette", "isCapital": false }, { "name": "Rock Springs", "isCapital": false }] }
    ];

export const CITIES: string[] = _.flatten(_.map(STATES, state => _.map(state.cities, city => city.name)));
